apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: shopx
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: authdb
  DB_USER: authuser
  DB_PASSWORD: StrongPassword@123
  ORDER_SERVICE_URL: http://order:8085

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: shopx
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "200m"
        sidecar.istio.io/proxyMemory: "64Mi"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
    spec:
      containers:
      - name: payment
        image: varunsoam/shopx-payment:399
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8087

        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: DB_PASSWORD

        - name: ORDER_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: payment-db-secret
              key: ORDER_SERVICE_URL

        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)

        - name: SPRING_DATASOURCE_USERNAME
          value: $(DB_USER)

        - name: SPRING_DATASOURCE_PASSWORD
          value: $(DB_PASSWORD)

        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update

        # ---- OpenTelemetry Configuration ----
        - name: OTEL_SERVICE_NAME
          value: "payment-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=shopx,deployment.environment=testing"

        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5

        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: shopx
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - name: http
      port: 8087
      targetPort: http
